name: Tests

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    - name: Install host app
      run: composer create-project --prefer-dist laravel/laravel host

    - name: Install package (this repo)
      uses: actions/checkout@v2
      with:
        path: host/packages/liberu-genealogy/laravel-gedcom
    
    - name: Require this package
      working-directory: ./host
      run: composer require liberu-genealogy/laravel-gedcom

    - name: Run tests
      working-directory: ./host      
      run: vendor/phpunit/phpunit/phpunit packages/liberu-genealogy/laravel-gedcom/tests
